### ISSUE TITLE
RFC en minusculas

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#105]
# Detalles
En el formulario de crear cliente
Si ingresas el RFC en minuscula marca error y no lo acepta en lugar de aceptarlo y parsearlo

## Descripción de la tarea

hacer que acepte el RFC en minuscula y solito lo parsee a mayuscula

**Comment by DHurtado714-itesm** [comment]
Lo mejor es que se deje asi, porque el parseo puede ocasionar problemas. El formato del RFC es en mayuscula, dejemoslo asi

**Comment by DenisseDB** [comment]
Entendido.
