### ISSUE TITLE
Numero de telefono permite mas de 10 digitos

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#108]
# Detalles
En el formulario de crear cliente, el numero de telefono te permite llear más de 10 números

## Descripción de la tarea

Topar el campo de numero de telefono para que no permita más de 10 númeross, ya que marca error al momento dee mandarlo, pero no te dice que es por que tienes más de 10 números

**Comment by DenisseDB** [comment]
Lo mandaré a PR, en unos momentos adjutno liga al PR

**Comment by DenisseDB** [comment]
VIDEO: https://drive.google.com/file/d/11ANxpBCR2RmC7dtho-jLW2isZ8e0nRSJ/view?usp=sharing
