### ISSUE TITLE
Status Done en tareas

### ISSUE THREAD

**Issue by DenisseDB** [Black-Dot-2024/Zeitgeist-FrontEnd#111]
Detalles
Las tareas en Done no están hasta abajo

Descripción de la tarea
Poner los que estan en status Done hasta abajo

**Comment by DenisseDB** [comment]
En ambos

**Comment by DenisseDB** [comment]
Todos los Done deben ir hasta abajo en todas las situaciones

**Comment by lCDSLl-Richard** [comment]
Tareas no es mío, así que lo voy a pasar, pero arreglo proyectos.
