### ISSUE TITLE
falla crear proyectos

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#120]
# Detalles
al tratar de crear proyectos, te da error

## Descripción de la tarea

checar por que da 401

## Imagen
![imagen](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/aafc979b-40da-4b4f-812f-0c5f01f45dc9)

**Comment by lCDSLl-Richard** [comment]
Ya fue arreglado.

**Comment by OlimpiaGarcia** [comment]
@lCDSLl-Richard  falta el costo del issue, no hay pr linkeado
