### ISSUE TITLE
No se renderizan las tasks

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#122]
# Detalles

en los proyetcos hay task, pero en la pestaña de tasks no aparecen

## Descripción de la tarea

checar eso :D

##image 

![imagen](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/49c498f5-40b6-4564-9a80-864849c3e500)

**Comment by salgue441** [comment]
Esa vista son de tus tareas asignadas, no de todas :)
