### ISSUE TITLE
Project task tiene que tener un scrollable

### ISSUE THREAD

**Issue by DHurtado714-itesm** [Black-Dot-2024/Zeitgeist-FrontEnd#125]
Deberia de tenter un scrollable para que no se corra infinitamente

**Comment by ArmandoRosasB** [comment]
Ya se habia resuetlo

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/113733780/c4c632e1-1941-4c8f-9583-5f88d5244b88)
