### ISSUE TITLE
ZG. Crear Layout personalizado

### ISSUE THREAD

**Issue by lCDSLl-Richard** [Black-Dot-2024/Zeitgeist-FrontEnd#17]
# Detalles

## Descripción de la tarea

Crear el Layout personalizado según el figma

## Criterios de Aceptación

- [x] Existe el Layout de manera personalizada

**Comment by lCDSLl-Richard** [comment]
Pueden actualizar link de pr y marcar la tarea como completada para poder cerrar el issue?

**Comment by DenisseDB** [comment]
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/pull/23
