### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by DHurtado714-itesm** [Black-Dot-2024/Zeitgeist-FrontEnd#173]
@FridaBG  no me aucerdo que era
Frida:
1. Si modifico únicamente al responsable de la tarea, no se actualiza y sigue apareciendo el mismo responsable. Solo se modifica si se cambia algún otro field.

2. Si le pongo en cancel, no me regresa a la pantalla anterior y borra todos los datos del modal

Pero le UI no esta consistente

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/81983296/e2c2ec30-2b76-4fda-8722-68a6ea815edd)

**Comment by dembA7** [comment]
[PR Backend](https://github.com/Black-Dot-2024/Zeitgeist-Backend/pull/155). Se solucionó el error de actualización en employee task.
