### ISSUE TITLE
ZG. Crear Cards personalizadas

### ISSUE THREAD

**Issue by lCDSLl-Richard** [Black-Dot-2024/Zeitgeist-FrontEnd#18]
# Detalles

## Descripción de la tarea
Crear cards personalizadas según el figma

## Criterios de Aceptación

- [x] Existe una cards personalizada según el figma

**Comment by sgarnica1** [comment]
Archivo: src/components/common/CardContainer.tsx

**Comment by sgarnica1** [comment]
Archivo: src/components/common/CardContainer.tsx
