### ISSUE TITLE
Extra Spacing

### ISSUE THREAD

**Issue by sebFlores02** [Black-Dot-2024/Zeitgeist-FrontEnd#183]
![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/82182557/7ceb27b5-0900-4a98-9e55-10f9452d4459)

**Comment by RodrigoTeran** [comment]
Si una Card llegara a ser más alta que las demás... ¿Quisieran que las demás se ajustaran a su alto? ¿O que se quedaran con su alto predefinido?

En otras palabras, ¿cómo quiéren que se vea? jaja
