### ISSUE TITLE
RF57 filtrar clientes por archivado

### ISSUE THREAD

**Issue by DiegoPerdomoS** [Black-Dot-2024/Zeitgeist-FrontEnd#218]
### Detalle del Issue

Cuando la filtras en cualquiera de las dos (archivado/No archivado) y no tiene clientes en ese filtro muestra la vista vacia

### Descripción de la tarea

El sistema muestra un mensaje al usuario para notificarle que no hay clientes en esta categoría

### Criterios de Aceptación

- [x] Ya se muestro algun avsio

### Evidencia

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/161071886/a23e44ce-56a0-45a1-ab79-dd55f90ff637)

**Comment by Ian326** [comment]
Modifica el Título para seguir el Estándar <Módulo>/RF57-<ID-Prueba>

**Comment by Ian326** [comment]
Ah caray, no se muestra. Se reabrirá.

**Comment by Ian326** [comment]
Ah carayy, se arreglo solo. I'm tripping
