### ISSUE TITLE
PAYED STATUS IN PROJECT

### ISSUE THREAD

**Issue by salgue441** [Black-Dot-2024/Zeitgeist-FrontEnd#269]
Payed status change not working, returns 403

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/75867326/39836e39-0b13-47b1-9e14-3373b5646892)

**Comment by Ian326** [comment]
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/3238c5fe-ecc6-45e8-a40b-6070b5dbe03b

Si funciona
