### ISSUE TITLE
Cuando le doy clic a editar una task, tengo que volver a darle click al icono del lapiz para editarlo

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#272]
Encontrado por: Charlie

**Comment by dembA7** [comment]
@OlimpiaGarcia 

te refieres a esto?

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93755653/564b044e-50ee-4c1d-9542-12a08d5d9039)

**Comment by salgue441** [comment]
Si es del dropdown, funciona el editar como deberia

**Comment by OlimpiaGarcia** [comment]
@salgue441  falta costo
