### ISSUE TITLE
task/RF02/Id:6,7,8 No se ordena correctamente

### ISSUE THREAD

**Issue by ArmandoRosasB** [Black-Dot-2024/Zeitgeist-FrontEnd#283]
# Detalle del Issue

Las tareas no se ordenan como dictan los cirterios de aceptacion

## Descripción de la tarea

Las tareas se deben ordenar por fecha de finalizacion, la tarea mas urgente (fecha de finalizacion mas proxima) debe estara mas arriba

## Evidencia del issue

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/113733780/1ea8c033-7554-4573-b083-0c7162812707)

**Comment by salgue441** [comment]
Se ordenan por end date dentro de cada proyecto
