### ISSUE TITLE
Sidebar employee appearing for everyone

### ISSUE THREAD

**Issue by salgue441** [Black-Dot-2024/Zeitgeist-FrontEnd#355]
## Detalle del Issue

The employee section appears for non admins

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/75867326/dca11bee-a6b9-4c3c-b2aa-43892091b200)

**Comment by DHurtado714-itesm** [comment]
https://github.com/orgs/Black-Dot-2024/projects/7/views/1?pane=issue&itemId=62557913

**Comment by DHurtado714-itesm** [comment]
Este issue esta repetido, no tengo problema si lo hacen ustedes, solo me confirman

**Comment by OlimpiaGarcia** [comment]
Nosotros lo hacemos Dani. Tranqui

**Comment by OlimpiaGarcia** [comment]
@salgue441  no tiene costo
