### ISSUE TITLE
Go Back

### ISSUE THREAD

**Issue by ArmandoRosasB** [Black-Dot-2024/Zeitgeist-FrontEnd#392]
## Descripción de la tarea

El boton de go back debe redirigir a la vista anterior exceptuando paginas de editar o paginas de crear

**Comment by OlimpiaGarcia** [comment]
no hay botón de go back en modify task, pero si en mdify project


![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/e1e07496-48d3-49cb-9339-2f825f494e6a)



![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/8f617b09-97d6-4b92-998b-33378deb5953)
