### ISSUE TITLE
PRO-RF16-Id:06,09, 14, /No se retroalimenta al usuario al modificar status

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#395]
## Descripción de la tarea

Al modificarse el status de un proyecto, debería salir un mensaje que informe que se modificó con éxito

## Criterios de Aceptación

- [ ] Sale un mensaje de éxito

**Comment by dembA7** [comment]
Ya se resolvió en el issue #379
