### ISSUE TITLE
Proyecto/RF28-10-11-18-19-26-27/ no muestra mensaje de retroalimetacion

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#397]
## Descripción de la tarea

no muestra mensaje de retroalimetacion

## Criterios de Aceptación

- [ ] Poner un mesanje de retroalimentacion

## Evidencia del issue

Imagen/Video

**Comment by Ian326** [comment]
- Duplicado de: #398
