### ISSUE TITLE
PRO-RF28-ID: 10-11-18-19-26-27/ no hya mensjae de retroaliementacion

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#398]
## Descripción de la tarea

No muestra mensaje de rtroalimentacion

## Criterios de Aceptación

- [ ] Muestra mensaje que sólo se pueden buscar reportes de tasks en done

## Evidencia del issue
![image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/838df87c-48d0-4919-9393-48c893cd8474)

**Comment by Ian326** [comment]
Me imagino que solo requiere cambiar el mensaje de la imagen de abajo. Algo así como "No tasks with this criteria were found"
