### ISSUE TITLE
proyecto-RF59-id: 7,8 Filtrar cuando no soy admin

### ISSUE THREAD

**Issue by sebFlores02** [Black-Dot-2024/Zeitgeist-FrontEnd#403]
# Detalle del Issue

Cuando soy del area de legal o contable me aparece la opción de filtrar los proyectos

## Descripción de la tarea

Según la prueba 7 y 8 del RF no debería de tener la opción para filtrar los proyectos cuando no soy administrador, lo cual no esta ocurriendo

## Evidencia del issue

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/82182557/f652394f-0c28-4183-8460-c5efe1365907)

**Comment by Ian326** [comment]
Duplicated of:
- #292 
- #293
