### ISSUE TITLE
Asignar departamento

### ISSUE THREAD

**Issue by salgue441** [Black-Dot-2024/Zeitgeist-FrontEnd#410]
## Detalle del Issue

No se asigna un departamento a un nuevo usuario ni a los usuarios existentes.

**Comment by RamonaNF** [comment]
Los admins qué rol tendrían?

O mejor que en la vista de employee haya otra columna para asignar departamento? 
Ya nada más si asignas un rol de legal o contable que en automático te asigne su departamento

@salgue441 @FridaBG 

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91426086/26cb5071-1fb6-44c8-99f3-90fcd8ad3cc8)
