### ISSUE TITLE
Cambio de rol no hace efecto hasta volver a hacer sign in

### ISSUE THREAD

**Issue by salgue441** [Black-Dot-2024/Zeitgeist-FrontEnd#413]
## Detalle del Issue

Al cambiar el rol a un usuario, no se hace el cambio de role hasta que el usuario vuelve a hacer sign in

**Comment by DHurtado714-itesm** [comment]
Es algo que no estaba contemplado en los criterios de aceptacion, puede no quedar a tiempo

**Comment by OlimpiaGarcia** [comment]
Falta costo
