### ISSUE TITLE
PRO/RF53-ID:01 y 03/Falta status pagado

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#431]
## Descripción de la tarea

no aparece status de pagado

## Criterios de Aceptación

- [x] Checar si es por algun error en la db o por que

## Evidencia del issue

Imagen/Video

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/a593b494-36d5-4a15-9c8a-603d02240673)

**Comment by RamonaNF** [comment]
Creo que solo debería aparecer para los proyectos que son chargeable

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91426086/aa8eda14-d7a1-4344-9e4a-8797aef62882)
