### ISSUE TITLE
task-/fecha da invalido

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#515]
## Descripción de la tarea

si borras la fecha con delete de tu teclado te marca error

## Criterios de Aceptación

- [ ] checarlo x_x

## Evidencia del issue

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91426086/7fd2b6e7-70d5-495d-b600-347d417f9313)

**Comment by Ian326** [comment]
Resuelto
