### ISSUE TITLE
Projct/Se pueden añadir opciones en el dropdown

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#518]
## Descripción de la tarea

En el dropdown de category de proyect puedes meter opiones desde la consola

## Criterios de Aceptación

- [ ] ¿Qué hay que hacer para arreglarlo?

## Evidencia del issue

Imagen/Video

**Comment by DHurtado714-itesm** [comment]
No es un issue
