### ISSUE TITLE
MOD-RF00-ID00/Fecha_Crear tarea y editar tarea

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#520]
## Descripción de la tarea

No deberias poder crear tareas des

## Criterios de Aceptación

- [ ] ¿Qué hay que hacer para arreglarlo?

## Evidencia del issue

Imagen/Video

**Comment by RamonaNF** [comment]
El rango de fechas valido para crear y modificar uan tarea debe ser entre 2018 y el año actual.
