### ISSUE TITLE
MOD-RF00-ID00/SideBar: Responsiveness no esta bien

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#523]
## Descripción de la tarea

Responsiveness no esta bien

## Criterios de Aceptación

- [x] ¿hacer responsive

## Evidencia del issue

Imagen/Video

**Comment by Ian326** [comment]
Podrías elaborar un poco más? Justo estaba trabajando en hacer la sidebar responsive yo 😬

**Comment by yna2131** [comment]
> Podrías elaborar un poco más? Justo estaba trabajando en hacer la sidebar responsive yo 😬

Ya lo arreglé hahaha, ahora aparece un icono de menu cuando la pagina se hace chiquito

**Comment by Ian326** [comment]
sip, perdona, no lo habia visto, haha.
