### ISSUE TITLE
Employee/No deja cambiar el rol de usuario

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#524]
## Descripción de la tarea

No deja cambiar el rol de usuario, y no se guarda

## Criterios de Aceptación

- [ ] No deja cambiar el rol de usuario, y no se guarda

## Evidencia del issue

Imagen/Video

**Comment by DHurtado714-itesm** [comment]
Funcion en local pero no en produccion
