### ISSUE TITLE
MOD-RF00-ID00/Go back sigue fallando

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#525]
## Descripción de la tarea

de project task me manda a task detail

## Criterios de Aceptación

- [ ] de project task me manda a task detail

## Evidencia del issue

Imagen/Video

**Comment by Ian326** [comment]
No lo puedo replicar en dev (Lo de dev se pasará a prod entre lo que subí esta respuesta y la mañana siguiente)
