### ISSUE TITLE
employees-RF00-ID00/falta la pantalla de no se enontraron

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#526]
## Descripción de la tarea

no hay pantalla

## Criterios de Aceptación

- [ ] ¿Qué hay que hacer para arreglarlo?

## Evidencia del issue

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/1987e2e5-cb14-422e-9c26-60355eab5087)

**Comment by DHurtado714-itesm** [comment]
No es crucial la verdad
