### ISSUE TITLE
task/Errores con las fechas

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#534]
## Descripción de la tarea

En un proyecto, creo una tarea, le asigo una due date.  no se registra en la vista esa fecha.

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/f16f4d40-40dd-45e2-a09e-2a19d8bfa93a)

 abro task detai ly sigue sn aparecer 

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/fd29e98f-5ce8-4a34-9acf-7373b25b904d)

cuando la edito, me pone por default la fehca del dia guiente

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/835ce6f0-8b0f-4544-82f4-c558b770d03c)

actualizo nuevamente la fecha a la que yo quiero y guardo. y por fin se actualiza en el task details

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/1a3893f6-a592-4516-9a4f-53a9c5aece8a)

y se actualiza en el en project details

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/2dc818b0-7cac-43f8-9795-202c7b1d64d7)

peroooo, en la pestaña de task de la side bar, parece un día anterior a la registrada

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/62e2aa08-8cc6-4ae5-bf1f-cbf3c91653ed)

**Comment by FridaBG** [comment]
✅ No se quien lo hizo pero ya está solucionado!
