### ISSUE TITLE
Proyecto-RF12/Ponerme de loco con las fechas

### ISSUE THREAD

**Issue by DiegoPerdomoS** [Black-Dot-2024/Zeitgeist-FrontEnd#543]
## Descripción de la tarea

- Empece a cambiar las fechas como loco y ya no me dice nada de porque no es valido
- Igualmente cuando si manda el aviso dice "invalid date" pero el usuario no sabe porque

## Criterios de Aceptación

- [ ] Que le diga al usuario porque no es valido la fecha
- [ ] Especificar porque la fecha no es valida cuando 

## Evidencia del issue

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/161071886/137e93b2-2ae0-4cb2-93bb-a2b7da3ac05a)

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/161071886/44e1a66c-6fcf-4b07-99bd-2a2e47c2d6e3)

**Comment by Ian326** [comment]
Podrías ser. Ese error en específico es pq la fecha límite inferior es 01/01/1900
