### ISSUE TITLE
Proyecto-RF12/Color de advertencia

### ISSUE THREAD

**Issue by DiegoPerdomoS** [Black-Dot-2024/Zeitgeist-FrontEnd#544]
## Descripción de la tarea

Nomas que en la verificación de la longitud de la descripción esta gris en lugar de rojo como todo lo demas

## Criterios de Aceptación

- [ ] Cambiarlo al color rojo

## Evidencia del issue

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/161071886/7f612672-ac95-403e-91cf-e26db0c41207)

**Comment by Ian326** [comment]
Ya cree un issue más específico para trabajar en todos los criterios de proyectos :)
