### ISSUE TITLE
Tasks/RF25-ID030, ID031 Fechas posteriores al fin del proyecto

### ISSUE THREAD

**Issue by RamonaNF** [Black-Dot-2024/Zeitgeist-FrontEnd#546]
## Descripción de la tarea
Una tarea puede tener fechas de inicio y fin posteriores a cuando acaba un proyecto

## Criterios de Aceptación

- [ ] Restringir fechas 
Podríamos restringir el rango de una tarea a la fecha de inicio y fin del proyecto 
O actualizar la endDate del proyecto si la tarea se pasa

## Evidencia del issue

TAREA QUE ACABA DESPUÉS

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91426086/2f863bf6-a496-479d-b409-59a389bec01c)

INFORMACIÓN CON LA QUE SE CREÓ

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91426086/1e98ee4f-4be9-4d09-8929-c4ee4e286dca)

**Comment by AdriftInVR** [comment]
De mis pruebas manuales del 17 de Mayo, se me pasó anotar este defecto

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/69860747/c504bdac-d7b8-416c-97ae-f05be40810ce)
