### ISSUE TITLE
Projects-RF12-ID00/Error al crear proyecto

### ISSUE THREAD

**Issue by RodrigoTeran** [Black-Dot-2024/Zeitgeist-FrontEnd#572]
## Descripción de la tarea
Al acceder a la ruta de `/projects/new` desde una página nueva no se muestra nada.

¿Qué esta mal?
No se muestra la página.

En la consola se muestra este error:
`Uncaught TypeError: Cannot read properties of null (reading 'role')`

## Criterios de Aceptación
- [ ] Checar que no se accedan a las variables cuando sean `null`.

## Evidencia del issue
![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/59104775/32eb8114-0d4a-4d27-b6b3-4b95e29ac7d8)

**Comment by Ian326** [comment]
Se arregló en develop (Será pusheado a prod entre el momento que se manda este mensaje y la mañana siguiente)
