### ISSUE TITLE
Project-RF15-ID00/Error de UI al actualizar el proyecto

### ISSUE THREAD

**Issue by RodrigoTeran** [Black-Dot-2024/Zeitgeist-FrontEnd#575]
## Descripción de la tarea
No hay consistencia en el UI cuando hay un error en actualizar proyecto.

¿Qué esta mal?
El banner de error de la descripción no es consistente con el banner de error de los demás inputs.

## Criterios de Aceptación

- [x] Mantener consistente el UI

## Evidencia del issue

Imagen/Video
![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/59104775/24011db7-3964-4f2d-b9fa-81b8fcc4896b)

**Comment by yna2131** [comment]
Ya se arregló
