### ISSUE TITLE
Project-RF16-ID00/Error de UI al consultar detalles de un proyecto

### ISSUE THREAD

**Issue by RodrigoTeran** [Black-Dot-2024/Zeitgeist-FrontEnd#576]
## Descripción de la tarea
Cuando la cantidad de caracteres del proyecto es muy alta la UI no se adapta correctamente.

¿Qué esta mal?
No me deje ver la información del proyecto adecuadamente.

## Criterios de Aceptación

- [x] Editar el UI para recortar el texto con un `wrap` para que cuando sea un texto sin espacios se corte bien.

## Evidencia del issue

Imagen/Video

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/59104775/1cc5373b-f863-4ab5-94a3-9abc10c41d47)

**Comment by yna2131** [comment]
Ya está resuelto
