### ISSUE TITLE
Responsividad /La barra de tarea esta larga

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-FrontEnd#645]
## Descripción de la tarea

La barra de busqueda esta muy larga en project y clients pero en employee chiquita

## Criterios de Aceptación

- [ ] Arreglarlo

## Evidencia del issue

se ve así en projects y clientes:

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/e459bcf7-62db-4687-a93a-35f5f01dd19f)

pero así en employees:
![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93570664/0890840a-51f4-4b60-8ccf-974dcdf937b7)

**Comment by DHurtado714-itesm** [comment]
El unico diferente es en employees. Todas las paginas estan con la barra larga. @sebFlores02 @sgarnica1 como queda mejor con lo responsivo
