### ISSUE TITLE
Notifications/RF31-ID40, 41

### ISSUE THREAD

**Issue by sgarnica1** [Black-Dot-2024/Zeitgeist-FrontEnd#656]
## Descripción de la tarea

Si el usuario intenta modificar el sistema para forzar el envio al departamento de notificación al mismo departamento, este debería mostrar un mensaje de error, pero sí permite enviar la notificación y muestra un mensaje de éxito

## Criterios de Aceptación

- [ ] Mostrar un mensaje de error que no se puede enviar notificación al mismo departamento

**Comment by DHurtado714-itesm** [comment]
![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/81983296/1d5b9e5b-5f6d-4665-8013-f56cd6e3df2e)
