### ISSUE TITLE
Todo el sistema/No hay internet

### ISSUE THREAD

**Issue by RamonaNF** [Black-Dot-2024/Zeitgeist-FrontEnd#673]
## Descripción de la tarea

Cuando no hay internet ya no se despliega el modal de sin conexión.

## Criterios de Aceptación

- [ ] Retroalimentación cuando no hay internet

## Evidencia del issue

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91426086/58336238-7706-41b4-ac0a-139949a90990)

**Comment by dembA7** [comment]
@DHurtado714-itesm @RamonaNF a mí me pasaba lo mismo pero el modal sí salía después de como 20-30 segundos
