### ISSUE TITLE
MOD-RF22/Al usuario eliminado debe de sacado de la plataforma

### ISSUE THREAD

**Issue by ArmandoRosasB** [Black-Dot-2024/Zeitgeist-FrontEnd#674]
## Descripción de la tarea
El usuario puede seguir navegando hasta que haga log out. No carga la informacion pero no redirige a login

## Criterios de Aceptación

- [ ] Al usuario eliminado debe de sacado de la plataforma
- [ ] Redirigir a login

**Comment by DHurtado714-itesm** [comment]
No se va a hacer, no hay tiempo
