### ISSUE TITLE
Proyectos-RF59-ID00Filtrar proyecto (archivado/no archivado/todos)

### ISSUE THREAD

**Issue by ArmandoRosasB** [Black-Dot-2024/Zeitgeist-FrontEnd#686]
## Descripción de la tarea

Como empleado de legal y contable, no puedo filtrar los proyectos por archivado, no archivado o todos.

## Criterios de Aceptación

- [ ] Poder filtrar proyectos si ssy empleado de legal o contable

## Evidencia del issue

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/113733780/78a7623a-61a5-4595-b7a9-8b624465e61d)

**Comment by dembA7** [comment]
el análisis dice que esto no es un defecto
