### ISSUE TITLE
Dropdown de roles

### ISSUE THREAD

**Issue by sgarnica1** [Black-Dot-2024/Zeitgeist-FrontEnd#89]
Los items en el dropdown de roles están repetidos

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/71858836/7a302e10-fbaa-462f-8468-467e48cf8db6)

**Comment by OlimpiaGarcia** [comment]
@sgarnica1 que base de datos tienes?? por que con la de staging ya estaba arrreglado

**Comment by lCDSLl-Richard** [comment]
Esto depende de la base de datos, solo hay que hacer limpieza
