### ISSUE TITLE
Des asignación de rol

### ISSUE THREAD

**Issue by sgarnica1** [Black-Dot-2024/Zeitgeist-FrontEnd#90]
Si el usuario actual es admin, y se cambia el rol a No Rol, el sistema no cierra su sesión y le permite seguir visitando las diferentes vistas, sin embargo, marca error en todas debido a que su rol no es válido en el backend

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/71858836/255fa2d1-8880-4c47-b2f7-c466bb895c0c)

**Comment by lCDSLl-Richard** [comment]
Editar Rol es de @RodrigoTeran
