### ISSUE TITLE
RF20 - Consultar reporte de un proyecto

### ISSUE THREAD

**Issue by FridaBG** [Black-Dot-2024/Zeitgeist-FrontEnd#94]
- [x] No se ven los acentos, aparece “??” en el lugar de la letra que lleva tilde.
- [x] Falta poder ver el área (legal o contable) al que pertenece al proyecto.
- [x] Los chips de estatus no siguen los colores ¿saben quién nos puede ayudar a resolver eso?

Gracias 😁

![Image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/105307730/9e890b60-aa7b-4182-ade2-ec5bce0b206d)

**Comment by ArmandoRosasB** [comment]
En el caso de los acentos, asi es como esta la informacion en la base de datos. Creo que el problema no es el front. Adjunto una imagen de la informacion de los proyectos en la base de datos.

![image](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/113733780/532cd9a8-1694-4023-ab6a-38e9ba65d9b1)
