### ISSUE TITLE
RF51 - Consultar proyectos

### ISSUE THREAD

**Issue by FridaBG** [Black-Dot-2024/Zeitgeist-FrontEnd#96]
¿Se puede usar la misma manera en que aparece la pantalla de carga que usa el de clients? 😁

https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/105307730/db37e331-9256-421f-bd8e-f3f38754e122

**Comment by lCDSLl-Richard** [comment]
Me parece que ya hay un esfuerzo para estadarizar los Loaders. Ping @dembA7

**Comment by Ian326** [comment]
Ya usan el mismo loader, solo que se cambio para que el de Clients usara el de Projects. JAJA
