### ISSUE TITLE
RF14 - Consultar proyectos de un cliente

### ISSUE THREAD

**Issue by FridaBG** [Black-Dot-2024/Zeitgeist-FrontEnd#99]
¿Será bueno que los proyectos dentro del perfil del cliente también puedan ser "clickeables" para poder ver su detalle así como en la vista de los proyectos? ¿Es sencillo de hacer?

**Comment by sebFlores02** [comment]
Sería ideal que si, creo que es parte de la user story consultar detalle de una tarea
